"""
ccflow - Claude Code CLI ↔ SDK Middleware

Production middleware bridging Claude Code CLI with SDK-like Python interfaces.
Enables subscription-based usage with TOON token optimization.

Example:
    >>> from ccflow import query, CLIAgentOptions
    >>> async for msg in query("Analyze this code", CLIAgentOptions(model="sonnet")):
    ...     print(msg.content, end="")
"""

from ccflow.api import batch_query, query
from ccflow.events import (
    CostIncurredEvent,
    CostTracker,
    Event,
    EventEmitter,
    EventType,
    LoggingHandler,
    MetricsHandler,
    SessionClosedEvent,
    SessionCreatedEvent,
    SessionDeletedEvent,
    SessionErrorEvent,
    SessionEvent,
    SessionLoadedEvent,
    SessionPersistedEvent,
    SessionResumedEvent,
    TokensUsedEvent,
    ToolCalledEvent,
    ToolResultEvent,
    TurnCompletedEvent,
    TurnStartedEvent,
    get_emitter,
    reset_emitter,
)
from ccflow.manager import SessionManager, get_manager, init_manager
from ccflow.metrics_handlers import (
    PrometheusEventHandler,
    setup_metrics,
    start_metrics_server,
)
from ccflow.rate_limiting import (
    CombinedLimiter,
    ConcurrencyLimiter,
    ConcurrencyLimitExceededError,
    RateLimitExceededError,
    RateLimiterStats,
    RetryHandler,
    SlidingWindowRateLimiter,
    TokenBucketRateLimiter,
    get_limiter,
    reset_limiter,
)
from ccflow.reliability import (
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitBreakerError,
    CircuitBreakerStats,
    CircuitState,
    HealthChecker,
    HealthStatus,
    RetryConfig,
    RetryExhaustedError,
    RetryStats,
    bind_correlation_id,
    calculate_delay,
    get_cli_circuit_breaker,
    get_correlation_id,
    get_health_checker,
    reset_cli_circuit_breaker,
    reset_health_checker,
    retry_with_backoff,
    set_correlation_id,
    with_retry,
)
from ccflow.exceptions import (
    CCFlowError,
    CLIAuthenticationError,
    CLIExecutionError,
    CLINotFoundError,
    CLITimeoutError,
    ParseError,
    PermissionDeniedError,
    SessionNotFoundError,
    SessionStoreError,
    ToonEncodingError,
)
from ccflow.pool import (
    PoolConfig,
    PoolStats,
    PoolTask,
    ProcessPool,
    StreamingPool,
    StreamingTask,
    TaskStatus,
    get_pool,
    get_streaming_pool,
    reset_pools,
)
from ccflow.pricing import (
    ModelPricing,
    ModelTier,
    UsageStats,
    calculate_cost,
    extract_model_from_events,
    extract_usage_from_events,
    get_pricing,
    get_usage_tracker,
    reset_usage_tracker,
    track_usage,
)
from ccflow.api_client import (
    APIClient,
    APIClientConfig,
    APIClientError,
    APINotAvailableError,
    APIRateLimitError,
    APIResponse,
    FallbackConfig,
    FallbackExecutor,
    get_api_client,
    get_fallback_executor,
    reset_api_client,
    reset_fallback_executor,
)
from ccflow.session import Session, load_session, resume_session
from ccflow.store import (
    BaseSessionStore,
    SessionFilter,
    SessionMetadata,
    SessionState,
    SessionStatus,
    SessionStore,
)
from ccflow.stores import MemorySessionStore, SQLiteSessionStore
from ccflow.types import (
    AssistantMessage,
    CLIAgentOptions,
    HookMessage,
    InitMessage,
    MCPServerConfig,
    Message,
    PermissionMode,
    QueryResult,
    ResultMessage,
    SessionStats,
    StopMessage,
    TextMessage,
    ToonConfig,
    ToolResultMessage,
    ToolUseMessage,
    UnknownMessage,
    UnknownSystemMessage,
    UserMessage,
)

__version__ = "0.1.0"
__all__ = [
    # Core API
    "query",
    "batch_query",
    "Session",
    "load_session",
    "resume_session",
    # Session Management
    "SessionManager",
    "get_manager",
    "init_manager",
    # Session Persistence
    "SessionStore",
    "BaseSessionStore",
    "SQLiteSessionStore",
    "MemorySessionStore",
    "SessionState",
    "SessionMetadata",
    "SessionFilter",
    "SessionStatus",
    # Events
    "Event",
    "EventType",
    "EventEmitter",
    "get_emitter",
    "reset_emitter",
    "SessionEvent",
    "SessionCreatedEvent",
    "SessionResumedEvent",
    "SessionClosedEvent",
    "SessionErrorEvent",
    "SessionPersistedEvent",
    "SessionLoadedEvent",
    "SessionDeletedEvent",
    "TurnStartedEvent",
    "TurnCompletedEvent",
    "ToolCalledEvent",
    "ToolResultEvent",
    "TokensUsedEvent",
    "CostIncurredEvent",
    "LoggingHandler",
    "MetricsHandler",
    "CostTracker",
    # Prometheus Metrics
    "PrometheusEventHandler",
    "setup_metrics",
    "start_metrics_server",
    # Rate Limiting
    "TokenBucketRateLimiter",
    "SlidingWindowRateLimiter",
    "ConcurrencyLimiter",
    "CombinedLimiter",
    "RetryHandler",
    "RateLimiterStats",
    "RateLimitExceededError",
    "ConcurrencyLimitExceededError",
    "get_limiter",
    "reset_limiter",
    # Reliability (Circuit Breaker, Retry, Health)
    "CircuitBreaker",
    "CircuitBreakerConfig",
    "CircuitBreakerError",
    "CircuitBreakerStats",
    "CircuitState",
    "get_cli_circuit_breaker",
    "reset_cli_circuit_breaker",
    "RetryConfig",
    "RetryExhaustedError",
    "RetryStats",
    "retry_with_backoff",
    "with_retry",
    "calculate_delay",
    "HealthChecker",
    "HealthStatus",
    "get_health_checker",
    "reset_health_checker",
    # Correlation IDs
    "get_correlation_id",
    "set_correlation_id",
    "bind_correlation_id",
    # Configuration
    "CLIAgentOptions",
    "ToonConfig",
    "MCPServerConfig",
    "PermissionMode",
    # Message types
    "Message",
    "InitMessage",
    "TextMessage",
    "ToolUseMessage",
    "ToolResultMessage",
    "StopMessage",
    "HookMessage",
    "AssistantMessage",
    "UserMessage",
    "ResultMessage",
    "UnknownSystemMessage",
    "UnknownMessage",
    # Results
    "QueryResult",
    "SessionStats",
    # Exceptions
    "CCFlowError",
    "CLINotFoundError",
    "CLIAuthenticationError",
    "CLIExecutionError",
    "CLITimeoutError",
    "SessionNotFoundError",
    "SessionStoreError",
    "ParseError",
    "ToonEncodingError",
    "PermissionDeniedError",
    # Process Pool
    "ProcessPool",
    "StreamingPool",
    "PoolConfig",
    "PoolStats",
    "PoolTask",
    "StreamingTask",
    "TaskStatus",
    "get_pool",
    "get_streaming_pool",
    "reset_pools",
    # Pricing and Usage
    "ModelPricing",
    "ModelTier",
    "UsageStats",
    "calculate_cost",
    "get_pricing",
    "extract_usage_from_events",
    "extract_model_from_events",
    "get_usage_tracker",
    "reset_usage_tracker",
    "track_usage",
    # API Fallback
    "APIClient",
    "APIClientConfig",
    "APIClientError",
    "APINotAvailableError",
    "APIRateLimitError",
    "APIResponse",
    "FallbackConfig",
    "FallbackExecutor",
    "get_api_client",
    "get_fallback_executor",
    "reset_api_client",
    "reset_fallback_executor",
]
